name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # ArangoDb.Abstractions.Query

    - name: Restore ArangoDb.Abstractions.Query
      run: dotnet restore ./src/*/ArangoDb.Abstractions.Query.csproj

    - name: Build ArangoDb.Abstractions.Query
      run: dotnet build ./src/*/ArangoDb.Abstractions.Query.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.IssuerSigningKey
      run: dotnet pack ./src/*/ArangoDb.Abstractions.Query.csproj --no-restore -o ~/nuget  -c Release

    # ArangoDb.Abstractions.Transaction

    - name: Restore ArangoDb.Abstractions.Transaction
      run: dotnet restore ./src/*/ArangoDb.Abstractions.Transaction.csproj

    - name: Build ArangoDb.Abstractions.Transaction
      run: dotnet build ./src/*/ArangoDb.Abstractions.Transaction.csproj --no-restore  -c Release

    - name: Pack ArangoDb.Abstractions.Transaction
      run: dotnet pack ./src/*/ArangoDb.Abstractions.Transaction.csproj --no-restore -o ~/nuget  -c Release

    # ArangoDb.Abstractions

    - name: Restore ArangoDb.Abstractions
      run: dotnet restore ./src/*/ArangoDb.Abstractions.csproj

    - name: Build ArangoDb.Abstractions
      run: dotnet build ./src/*/ArangoDb.Abstractions.csproj --no-restore  -c Release

    - name: Pack ArangoDb.Abstractions
      run: dotnet pack ./src/*/ArangoDb.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    #ArangoDb.Api

    - name: Restore ArangoDb.Api
      run: dotnet restore ./src/*/ArangoDb.Api.csproj

    - name: Build ArangoDb.Api
      run: dotnet build ./src/*/ArangoDb.Api.csproj --no-restore  -c Release

    - name: Pack ArangoDb.Api
      run: dotnet pack ./src/*/ArangoDb.Api.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
